### ISSUE TITLE
Add "Who is Contributing" on the README

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#105]
add a new section like this:

![image](https://github.com/vczb/sagu-ui/assets/51221635/f37851b2-11e4-4dbe-94d4-0be63021b31f)

https://github.com/vczb/gamou#who-is-contributing

**Comment by geekyharsh05** [comment]
Can you assign this to me?

**Comment by geekyharsh05** [comment]
@vczb Can you please review this?

**Comment by vczb** [comment]
> @vczb Can you please review this?

well done my friend, approved and merged with hacktoberfest-accepted label :)

keep coming
