### ISSUE TITLE
Add emoji for each heading section on README

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#107]
Please, add a cool emoji for each section. like this one:

![image](https://github.com/vczb/sagu-ui/assets/51221635/5817f18c-cbc0-47a6-964a-2ac152ab9c14)

---

the section list

- [Installation](https://github.com/vczb/sagu-ui#installation)
- [Usage](https://github.com/vczb/sagu-ui#usage)
- [Theme customization](https://github.com/vczb/sagu-ui#theme-customization)
- [Component customization](https://github.com/vczb/sagu-ui#component-customization)
- [Examples](https://github.com/vczb/sagu-ui#examples)
- [Contributing](https://github.com/vczb/sagu-ui#contributing)
- [What is inside?](https://github.com/vczb/sagu-ui#what-is-inside)
- [Available commands](https://github.com/vczb/sagu-ui#available-commands)
- [Project structure](https://github.com/vczb/sagu-ui#project-structure)
- [Our Amazing Contributors 🌟](https://github.com/vczb/sagu-ui#our-amazing-contributors-) // this section already have emoji
- [License](https://github.com/vczb/sagu-ui#license)

---

be creative

**Comment by Divyesh1511** [comment]
hey @vczb hope you are doing well, so can you please assign me this task
