### ISSUE TITLE
How about adding a Toast Component?

### ISSUE THREAD

**Issue by KushalNerella07** [vczb/sagu-ui#117]
Hey there,

Been playing around with saga-ui and thought – why not have a Toast component? Toasts are like those pop-ups you see when something happens, like a heads-up or a quick "you did this" message.

Basic Ideas:

Variants: Thinking about the usual ones like Success or Error.
Position: Top-right corner seems cool.
Duration: Not too long, not too short. Just enough to read.
Dismiss: A little 'X' or a tap/click to make it go away?
Would love to take a shot at it and see how it goes. What do you think?

**Comment by vczb** [comment]
> Hey there,
> 
> Been playing around with saga-ui and thought – why not have a Toast component? Toasts are like those pop-ups you see when something happens, like a heads-up or a quick "you did this" message.
> 
> Basic Ideas:
> 
> Variants: Thinking about the usual ones like Success or Error. Position: Top-right corner seems cool. Duration: Not too long, not too short. Just enough to read. Dismiss: A little 'X' or a tap/click to make it go away? Would love to take a shot at it and see how it goes. What do you think?

hey thanks for suggesting :)

we have the alert component https://vczb.github.io/sagu-ui/?path=/story/alert--default 

maybe the Toast can implement the Alert, as children or something similar

feel free to experiment and figure out the best approach

thanks :rocket:
