### ISSUE TITLE
How about a Tooltip Component?

### ISSUE THREAD

**Issue by KushalNerella07** [vczb/sagu-ui#118]
Hey team,

So, I was thinking, tooltips are pretty handy, right? They're like little hints that show up when you hover over something. Thought it might be cool to have in saga ui.

Basic Ideas:

Positioning: Maybe have it pop up at the bottom?
Content: Just some text to start with.
Delay: A quick pop after hovering?
Arrow: A little arrow pointing at the thing?
I'd love to give it a try if everyone's on board. Thoughts?

**Comment by vczb** [comment]
> Hey team,
> 
> So, I was thinking, tooltips are pretty handy, right? They're like little hints that show up when you hover over something. Thought it might be cool to have in saga ui.
> 
> Basic Ideas:
> 
> Positioning: Maybe have it pop up at the bottom? Content: Just some text to start with. Delay: A quick pop after hovering? Arrow: A little arrow pointing at the thing? I'd love to give it a try if everyone's on board. Thoughts?

great idea, you are welcome to implement it :)

**Comment by vczb** [comment]
closed by https://github.com/vczb/sagu-ui/pull/120
