### ISSUE TITLE
Create Avatar component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#17]
check other components to undestand the style-guide and patterns

example avatar component:

https://mui.com/material-ui/react-avatar/

**Comment by yamitrvg12** [comment]
Hey [vczb](https://github.com/vczb), can you assign me this task so that I can work on it?

**Comment by vczb** [comment]
> Hey [vczb](https://github.com/vczb), can you assign me this task so that I can work on it?

Go ahead!!! :fire:

**Comment by yamitrvg12** [comment]
Hey [vczb](https://github.com/vczb) I have completed this task https://github.com/vczb/sagu-ui/pull/24. Could you please take a look it and if everything is OK could you please merge and add the "hacktoberfest-accepted" tag to it. Thank you!

**Comment by vczb** [comment]
Closed by #24
