### ISSUE TITLE
Create Alert component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#18]
- check the other components to undertand the pattern and style-guide
- should be reusable

Alert example: 

https://mui.com/material-ui/react-alert/

**Comment by yamitrvg12** [comment]
Hey [vczb](https://github.com/vczb), can you assign me this task so that I can work on it?

**Comment by vczb** [comment]
> Hey [vczb](https://github.com/vczb), can you assign me this task so that I can work on it?

Assigned! thank you :rocket:

**Comment by yamitrvg12** [comment]
working on it...

**Comment by yamitrvg12** [comment]
Hey [vczb](https://github.com/vczb) I have completed this task https://github.com/vczb/sagu-ui/pull/38. Could you please take a look it and if everything is OK could you please merge and add the "hacktoberfest-accepted" tag to it. 
Thank you!

**Comment by vczb** [comment]
> Hey [vczb](https://github.com/vczb) I have completed this task #38. Could you please take a look it and if everything is OK could you please merge and add the "hacktoberfest-accepted" tag to it. Thank you!

Ok, I will review it ASAP. don't worry about the CI, I will fix the build error later

**Comment by yamitrvg12** [comment]
[vczb](https://github.com/vczb) I saw that you merged :), could you please add "hacktoberfest-accepted" tag to it.

**Comment by vczb** [comment]
> > Hey [vczb](https://github.com/vczb) I have completed this task #38. Could you please take a look it and if everything is OK could you please merge and add the "hacktoberfest-accepted" tag to it. Thank you!
> 
> Ok, I will review it ASAP. don't worry about the CI, I will fix the build error later

Is already added

![image](https://user-images.githubusercontent.com/51221635/193903925-bb50c643-e0ec-4bd8-b4c6-6e138f2c7a4a.png)

**Comment by vczb** [comment]
Closed by #38

**Comment by yamitrvg12** [comment]
awesome, thank you [vczb](https://github.com/vczb)
