### ISSUE TITLE
Create Rating component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#20]
check the other components to undertand the patterns and styles

reference: https://mui.com/material-ui/react-rating/

**Comment by gokhalevedant06** [comment]
Hello @vczb, I would like to work on this issue

**Comment by alkhimch** [comment]
Please assign to me this task. I made similar component in vue . 
![image](https://user-images.githubusercontent.com/51736616/193443193-774501d4-4d21-4a3a-8b2b-c440ac481d49.png)

**Comment by vczb** [comment]
> Hello @vczb, I would like to work on this issue

thanks @gokhalevedant06 go ahead!

**Comment by vczb** [comment]
> Please assign to me this task. I made similar component in vue . This component can any float value describe. ![image](https://user-images.githubusercontent.com/51736616/193443193-774501d4-4d21-4a3a-8b2b-c440ac481d49.png)

hi @alkhimch he already has another developer asigned to it, feel free to check other issues and jump on it

**Comment by vczb** [comment]
> Hello @vczb, I would like to work on this issue

hi @gokhalevedant06 are you still working on that?

**Comment by gokhalevedant06** [comment]
> > Hello @vczb, I would like to work on this issue
> 
> hi @gokhalevedant06 are you still working on that? 

Nope. Sorry couldn't do it

**Comment by vczb** [comment]
> > > Hello @vczb, I would like to work on this issue
> > 
> > 
> > hi @gokhalevedant06 are you still working on that?
> 
> Nope. Sorry couldn't do it

@gokhalevedant06 

Don't worry. Feel free to join back when you can! Always welcome

**Comment by charlygg** [comment]
Hi, Can I try this component?

**Comment by vczb** [comment]
> Hi, Can I try this component?
> 
> I am more a Javascript developer but encourage to learn Typescript (y)

Hello! go ahead! :fire:

**Comment by vczb** [comment]
this issue is still open

**Comment by KeerthanaR29** [comment]
Hello @vczb. Please assign me to this issue
