### ISSUE TITLE
Create Range component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#21]
check the other components to undertand the style-guide and patterns

---

- should be single or double
- optional primary or secondary color

range reference:

https://codepen.io/vczb/pen/zYvWjyj

feel free to be creative

**Comment by Shivam256** [comment]
Can I work on this issue?

**Comment by vczb** [comment]
> Can I work on this issue?

go ahead!

**Comment by Shinji22** [comment]
Hey, can i work on this issue?

**Comment by vczb** [comment]
closed by #52
