### ISSUE TITLE
Add dots to slider

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#3]
create a new optional prop named `dots` ( default false ) that increment dots for each slide that we have on the slider. 

when the user click on the dot ( eg 3 ) should go to the slide 3

use [the slide Single Item](https://react-slick.neostack.com/) as exemple of behaviour

create beautiful dots, follow or current style-guide ( colors, shadows, etc )

[here](https://vczb.github.io/sagu-ui/?path=/story/slider--default) is our slider component

note: single image should not render the dot

**Comment by AsmaKacem1** [comment]
Hi @vczb 
can i work on this issue?

**Comment by vczb** [comment]
> Hi @vczb can i work on this issue?

Sure! I'll sign you on it

**Comment by vczb** [comment]
> Hi @vczb can i work on this issue?

hi @AsmaKacem1 are you still working on that?

**Comment by maemreyo** [comment]
Let's assign it to me, I will work on it. Thanks! @vczb

**Comment by vczb** [comment]
> Ive created a PR #65 for this issue, please take a look. Thanks @vczb

Hello, I will review ASAP

**Comment by vczb** [comment]
Closed by #65
