### ISSUE TITLE
Add some example to EXAMPLES.md

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#31]
Create a [codesandbox](https://codesandbox.io/) ( or other ) examples and add it to the EXAMPLES.md file.

--- 

No limit of examples, more than 1 developer can join on this issue. Feel free to submit your PR.

**Comment by yash6318** [comment]
hey @vczb  can you assign this to me? I'd love to contribute..

**Comment by Shailendra1703** [comment]
hey @vczb can you also assign this to me , I  would  also like to contribute

**Comment by ugwustanley** [comment]
Hi @vczb can I also contribute to this ?

**Comment by sai-karthik-p** [comment]
Hi @vczb, can you also assign this to me? I'd like to contribute.

**Comment by amitkroutthedev** [comment]
Hi @vczb, can you also assign this to me? I'd like to contribute.

**Comment by amitkroutthedev** [comment]
@vczb  is this project is included in hacktoberfest

**Comment by vczb** [comment]
> @vczb is this project is included in hacktoberfest

yes it is, I already add the approval tags to your PR #45
