### ISSUE TITLE
Create Pagination component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#35]
- Check the other components to understand the design system and the patterns

Pagination reference:

https://mui.com/pt/material-ui/react-pagination/

**Comment by KIET7UKE** [comment]
Hey, can i take this up?

**Comment by vczb** [comment]
> Hey, can i take this up?

Go ahead!

**Comment by KIET7UKE** [comment]
Hey, @vczb how to run this program in vscode? It's not starting with npm start.

**Comment by vczb** [comment]
> Hey, @vczb how to run this program in vscode? It's not starting with npm start.

`yarn sb`

![image](https://user-images.githubusercontent.com/51221635/194713286-6d48e3ed-b230-49a9-b073-7a3663aaba3e.png)

**Comment by vczb** [comment]
> Hey, @vczb how to run this program in vscode? It's not starting with npm start.

hi @KIET7UKE are you still working on that?

**Comment by maemreyo** [comment]
Hi @vczb, please assign me this issue. Tomorrow I will work on it. Thanks!

**Comment by vczb** [comment]
> Hi @vczb, please assign me this issue. Tomorrow I will work on it. Thanks!

Cool! Its all yours

**Comment by maemreyo** [comment]
I want to get counted in hacktoberfest. I joined late lol

**Comment by vczb** [comment]
> I want to get counted in hacktoberfest. I joined late lol

still in time! :rocket:

**Comment by maemreyo** [comment]
Yes, I'm trying to get counted asap, lol. Thanks for supporting me 👯

**Comment by maemreyo** [comment]
Hi there @vczb , I created a PR #67 to solve the pagination issue. Please take a look!
Thanks!

**Comment by vczb** [comment]
@maemreyo great job

**Comment by vczb** [comment]
closed by #67
