### ISSUE TITLE
Create Table component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#46]
- should be reusable
- use the same pattern / style-guide to the other components

table reference:

https://mui.com/material-ui/react-table/

**Comment by zainulabideen1122** [comment]
@vczb  i want to create the table component in React, is there any issue in it? if not then kindly assign this task to me

**Comment by vczb** [comment]
> @vczb i want to create the table component in React, is there any issue in it? if not then kindly assign this task to me

Cool! thanks for your interest, go ahead =)

**Comment by vczb** [comment]
> @vczb i want to create the table component in React, is there any issue in it? if not then kindly assign this task to me

hi @zainulabideen1122  are you still working on it?

**Comment by vczb** [comment]
this issue is still open

**Comment by shlok-2003** [comment]
Hey @vczb, I want to contribute to this issue. Can you assign it to me.

**Comment by vczb** [comment]
> Hey @vczb, I want to contribute to this issue. Can you assign it to me.

yes, go ahead :)

**Comment by shlok-2003** [comment]
Hey @vczb, Can you elaborate more on this issue, or is there any slack / discord channel for this repo

**Comment by vczb** [comment]
> Hey @vczb, Can you elaborate more on this issue, or is there any slack / discord channel for this repo

there is no channel, let's coordinate here on the issue

---

context:

you should create a component for rendering tables https://www.w3schools.com/html/html_tables.asp , the API should be similar to this one https://mui.com/material-ui/react-table/

![image](https://github.com/vczb/sagu-ui/assets/51221635/9b341027-0cba-481e-ba0a-c58ddfcad955)

remind to check other components to understand the project patterns

feel free to explore other table component examples and if you have any questions I will be glad to help you

**Comment by shlok-2003** [comment]
I am trying to run `yarn sb`, but it throws an error 
`$ NODE_OPTIONS=--openssl-legacy-provider storybook dev -p 6006
'NODE_OPTIONS' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.`. 

I tried to google it out, making changes in env file, but nothing has resolved this error

**Comment by vczb** [comment]
> I am trying to run `yarn sb`, but it throws an error `$ NODE_OPTIONS=--openssl-legacy-provider storybook dev -p 6006 'NODE_OPTIONS' is not recognized as an internal or external command, operable program or batch file. error Command failed with exit code 1.`.
> 
> I tried to google it out, making changes in env file, but nothing has resolved this error

I just cloned the project and reinstalled it from scratch and seems to be working here... please make sure you are using nodejs v18.16.0 and you installed the project using yarn. 

If the problem persists, please share your setup environment windows / mac / linux (distro).

you also can try to run the storybook directly using the command: `yarn storybook dev -p 6006`
