### ISSUE TITLE
Create Breadcrumb component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#47]
- should be reusable
- follow the same pattern / style-guide from the other components

reference:

https://mui.com/material-ui/react-breadcrumbs/

**Comment by NirvanaPhX** [comment]
Can I take a shot on this?

**Comment by vczb** [comment]
> Can I take a shot on this?

Go ahead! :rocket:

**Comment by NirvanaPhX** [comment]
Hi @vczb I just got busy recently and I don't think I will have time to work on this for quite some time. I don't want to take it so no one else can work on it. 
I will check back when I am free. If it is still open, I will go back working on it. 
Sorry about the inconvenience.

**Comment by vczb** [comment]
> Hi @vczb I just got busy recently and I don't think I will have time to work on this for quite some time. I don't want to take it so no one else can work on it. I will check back when I am free. If it is still open, I will go back working on it. Sorry about the inconvenience.

hi @NirvanaPhX  don't worry. thanks for the status report

**Comment by Shinji22** [comment]
Hi @vczb, can I take this issue?

**Comment by vczb** [comment]
> Hi @vczb, can I take this issue?

go ahead!

**Comment by vczb** [comment]
Closed by #53
