### ISSUE TITLE
Create Stepper component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#48]
- should be reusable
- follow the same pattern / style-guide from the others

reference:

https://mui.com/material-ui/react-stepper/

**Comment by Rafajrg21** [comment]
Hi @vczb, I would like to try and make this component

**Comment by vczb** [comment]
> Hi @vczb, I would like to try and make this component

Sure! go ahead

**Comment by vczb** [comment]
> Hi @vczb, I would like to try and make this component

hi @Rafajrg21 are you still working on it?

**Comment by Rafajrg21** [comment]
Sorry @vczb I've been busy with some work stuff but I will be free since this monday and I still want to work on this if that's ok

**Comment by vczb** [comment]
this issue is still open

**Comment by siddarthpai** [comment]
Hey ! I would love to work on this

**Comment by vczb** [comment]
> Hey ! I would love to work on this

you are welcome :)
