### ISSUE TITLE
Create Skeleton component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#49]
- should be reusable
- follow the same patterns at the other components

reference:

https://mui.com/material-ui/react-skeleton/

**Comment by helloshiv01** [comment]
please assign me this issue

**Comment by helloshiv01** [comment]
please elaborate on the issue

**Comment by vczb** [comment]
> please elaborate on the issue

you need to create a Component that support different types of skeletons ( loaders ) 

ex:

![image](https://user-images.githubusercontent.com/51221635/196047352-66ae3eb7-f442-4b6d-8da7-34e511fce9f2.png)

![image](https://user-images.githubusercontent.com/51221635/196047361-a90b42eb-52c8-438c-825d-dcd1e3e68fa4.png)

![image](https://user-images.githubusercontent.com/51221635/196047371-7098524e-3436-4461-b4eb-1e1a136b0203.png)


## Tip:

you can use the https://github.com/vczb/sagu-ui/blob/main/src/animations/placeholder.ts placeholder animation to create a background.

**Comment by maemreyo** [comment]
@vczb Hi there! Can I work on this!?

**Comment by maemreyo** [comment]
I have almost done with this issue; please assign it to me, thanks! @vczb

**Comment by maemreyo** [comment]
Ive created this PR to solve this issue #64 . Please take a look.

**Comment by vczb** [comment]
> Ive created this PR to solve this issue #64 . Please take a look.

thanks @maemreyo , I will review ASAP

**Comment by vczb** [comment]
Closed by #64
