### ISSUE TITLE
BUG - Deprecation Warning

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#55]
## Deprecation Warning on console

to reproduce: 

Run the command

```
$ yarn lint
```

```
(node:73477) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./2020/" in the "exports" field module resolution of the package at /home/vini/src/sagu-ui/node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./2020/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:73477) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./helpers/" in the "exports" field module resolution of the package at /home/vini/src/sagu-ui/node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./helpers/*".
```

**Comment by vczb** [comment]
> I also tried for node v14 and v12 in which it doesn't seem to appear.. If you are still getting the error, what you can try is removing line highlighted in red and mapping ./* to ./* like highlighted in green (in **package.json**) <img alt="image" width="128" src="https://user-images.githubusercontent.com/76804118/197772786-0a57e64a-c866-4041-a954-2ddc5867fac0.png">
> 
> Not raising a PR as I am not able to reproduce the error

Thanks for noticing that. I will check ASAP

**Comment by keerthanak-tw** [comment]
I cannot see this ./ mapping in package.json.. So try adding the mentioned line in file.. 
Then you need to add exports and add it..
Reference: https://github.com/postcss/postcss/commit/92155c73e105a36af5196a75bcc34ada377a711f

**Comment by vczb** [comment]
Seems to be fixed... I can't reproduce, feel free to reopen in case of it back
