### ISSUE TITLE
Create Github actions - Best practices

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#59]
# Should create a new action workflow that verify best practices

Best practices rules:

1. Only one commit per PR

---

Only these rule for now.

**Comment by vczb** [comment]
> 

Hi @keerthanak-tw nice catch! Feel free to create a new issue or submit the PR directly.

**Comment by vczb** [comment]
@keerthanak-tw 

Just to double-check, confirm if you are working on this current issue #59 

If yes I will assign you to that

**Comment by keerthanak-tw** [comment]
Hello.. Iam not working on this or the one i mentioned. But wanted to bring attention when i noticed it..
Will create a new issue for others to pick up

**Comment by vczb** [comment]
> Hello.. Iam not working on this or the one i mentioned. But wanted to bring attention when i noticed it.. Will create a new issue for others to pick up

Cool, thanks for the report. Feel free to create a new issue, someone can jump on it =)

**Comment by vczb** [comment]
this issue is no longer aplicable since we can set up squash and merge on the github

![image](https://github.com/vczb/sagu-ui/assets/51221635/b5475e49-a490-4842-a2ec-55f5c85f47b9)
