### ISSUE TITLE
Add placement left to paper

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#6]
https://vczb.github.io/sagu-ui/?path=/story/paper--default

**Comment by anechol** [comment]
Hey, how's it going? I'm trying to submit a PR for this issue for Hacktoberfest but I'm having some issues pushing my branch. I've tried both HTTPS and SSH and still no luck. Anything I'm missing here?

**Comment by vczb** [comment]
> Hey, how's it going? I'm trying to submit a PR for this issue for Hacktoberfest but I'm having some issues pushing my branch. I've tried both HTTPS and SSH and still no luck. Anything I'm missing here?

Hi @anechol , so strange, this repo doesn't have anything different. Can you please share the error message

**Comment by anechol** [comment]
So with https, I'm getting the following error:

`fatal: unable to access 'https://github.com/vczb/sagu-ui.git/': The requested URL returned error: 403`

I have a personal access token created and have been using that. I have also tried SSH. I have a key added to my account and the ssh agent and all of that and still getting this error:

```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I might be missing something here, but I am able to push to own repos just fine. 🤔 I am using WSL2 if that matters, but I haven't had this issue before.

**Comment by vczb** [comment]
> 

did you create a new branch ? 

`git checkout -b my-branch-name`

**Comment by vczb** [comment]
> So with https, I'm getting the following error:
> 
> `fatal: unable to access 'https://github.com/vczb/sagu-ui.git/': The requested URL returned error: 403`
> 
> I have a personal access token created and have been using that. I have also tried SSH. I have a key added to my account and the ssh agent and all of that and still getting this error:
> 
> ```
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> I might be missing something here, but I am able to push to own repos just fine. thinking I am using WSL2 if that matters, but I haven't had this issue before.

you need fork this repository and create a new branch to submit a PR

guides: 

1. https://opensource.com/article/19/7/create-pull-request-github
2. https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by anechol** [comment]
AH I missed the forking step haha. Thanks, I'll get a PR up later and see your thoughts on it.

**Comment by vczb** [comment]
> AH I missed the forking step haha. Thanks, I'll get a PR up later and see your thoughts on it.

You are welcome, any questions I'm available
