### ISSUE TITLE
Upgrade github actions node version

### ISSUE THREAD

**Issue by keerthanak-tw** [vczb/sagu-ui#61]
Github actions have started using node 16 and the usage of old version is leading to the following warning:
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/76804118/197580775-b97d666c-815d-4c11-a74b-121974c27dd4.png">

More information on what needs to be done can be found in this [github blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

**Comment by vczb** [comment]
> Github actions have started using node 16 and the usage of old version is leading to the following warning: <img alt="image" width="1416" src="https://user-images.githubusercontent.com/76804118/197580775-b97d666c-815d-4c11-a74b-121974c27dd4.png">
> 
> More information on what needs to be done can be found in this [github blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

Thanks for report

**Comment by GbotemiB** [comment]
HI @keerthanak-tw. I will love to work on this issue. Can you assign this to me?

**Comment by vczb** [comment]
> HI @keerthanak-tw. I will love to work on this issue. Can you assign this to me?

Sure! go ahead :fire:

**Comment by vczb** [comment]
this issue is still open

**Comment by keerthanak-tw** [comment]
@vczb I have upgraded and the ci workflow passed successfully. Please have a look at PR #69

**Comment by vczb** [comment]
> @vczb I have upgraded and the ci workflow passed successfully. Please have a look at PR #69

Great job! :rocket:
