### ISSUE TITLE
Test some component with jest

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#7]
we already have a lot of unit tests on the codebase, but not all components are tested, feel free to choose one and test it. Take a loot on the others to reference

**Comment by Lofty-Brambles** [comment]
Hi, @vczb I'd like to work on this issue!

**Comment by vczb** [comment]
> Hi, @vczb I'd like to work on this issue!

go ahead :rocket:

**Comment by Balastrong** [comment]
I'll have a look at some tests as well, there are quite a few components untested :D

**Comment by vczb** [comment]
> I'll have a look at some tests as well, there are quite a few components untested :D
@Balastrong sure! feel free to create an issue describing what component you want to test :smile:

**Comment by anechol** [comment]
I need practice with TS and testing so I will likely grab a component or two to add tests to as well.

**Comment by vczb** [comment]
More then 1 dev can work on this issue. Feel free to test some component/behavior and submit your PR
