### ISSUE TITLE
Fix typo on README in the customization section

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#72]
https://github.com/vczb/sagu-ui#component-customization

![image](https://user-images.githubusercontent.com/51221635/234554336-e8c69a9b-fd43-43fb-a8d5-ccf540dd0fc1.png)

need to add a missing "O"

---

correct sentence:

"You have too many ways to customize the Sagu components"

**Comment by Deveesh-Shetty** [comment]
On it!
