### ISSUE TITLE
Fix typo on README

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#78]
on the readme we have this text "styled-components are required"

![image](https://github.com/vczb/sagu-ui/assets/51221635/a236a1bd-5015-4fe0-9fd3-6ec1d13ba01e)

should be:

`_[styled-components](https://github.com/styled-components/styled-components) package is required_`

it should look like this:

_[styled-components](https://github.com/styled-components/styled-components) package is required_

**Comment by saisram** [comment]
Hi... could this be assigned to me?

**Comment by vczb** [comment]
> Hi... could this be assigned to me?

feel free to work on it :)

**Comment by vczb** [comment]
closed by https://github.com/vczb/sagu-ui/pull/81
