### ISSUE TITLE
Create a modal component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#8]
create a new component following the pattern/style-guide of the components that we already have.

Any questions I'm glad to help

**Comment by Shinji22** [comment]
Hi, @vczb I'd like to work on this issue :)

**Comment by vczb** [comment]
> Hi, @vczb I'd like to work on this issue :)

Go ahead! :rocket:

**Comment by Shinji22** [comment]
Hey @vczb, I have some questions about the implementation.
Do you want a simple empty modal, and let the user display the elements in it freely (like MUI https://mui.com/material-ui/react-modal/#basic-modal)? Or something more structurated, with a body, and optionnal header and footer (like bootstrap https://getbootstrap.com/docs/4.0/components/modal/#live-demo)?

**Comment by vczb** [comment]
> Hey @vczb, I have some questions about the implementation. Do you want a simple empty modal, and let the user display the elements in it freely (like MUI https://mui.com/material-ui/react-modal/#basic-modal)? Or something more structurated, with a body, and optionnal header and footer (like bootstrap https://getbootstrap.com/docs/4.0/components/modal/#live-demo)?

Nice, question. Let's implement a complete modal with body/header/footer ( bootstrap )

thanks for asking

**Comment by Shinji22** [comment]
OK, perfect, that's how I started to implement it :)

**Comment by vczb** [comment]
Closed by #29
