### ISSUE TITLE
Update storybook to latest

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#83]
Update the package to the latest stable version

https://storybook.js.org/

- make sure that you do not introduce any breaking change
- build the storybook to double-check the building

**Comment by aalmeida00** [comment]
Hi @vczb, I would like to do this update.

**Comment by vczb** [comment]
> Hi @vczb, I would like to do this update.

hey @aalmeida00  feel free to go ahead :heart:

**Comment by vczb** [comment]
closed by https://github.com/vczb/sagu-ui/pull/91
