### ISSUE TITLE
Refactor: Move spacingModifier file

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#85]
move the file [spacingModifier](https://github.com/vczb/sagu-ui/blob/main/src/utils/spacingModifier.ts) to the [styles](https://github.com/vczb/sagu-ui/tree/main/src/styles) dir

change all related imports

make sure nothing is broking

---

**optional:**
_you can move using git mv_

note: if you don't know how to use it, just move it at any way

**Comment by siddarthpai** [comment]
hey can i work on this!

**Comment by vczb** [comment]
> hey can i work on this!

Hey! I'm glad you back. I will review your PR right now

**Comment by vczb** [comment]
Closed by https://github.com/vczb/sagu-ui/pull/86
