### ISSUE TITLE
Create a AutoComplete component

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#9]
create a new component following the same pattern/style-guide as the other components that we have.

---

AutoComplete behaviour reference: https://mui.com/pt/material-ui/react-autocomplete/

**Comment by Im-Kunal-13** [comment]
@vczb Can you assign me this issue? I would like to work on it

**Comment by yamitrvg12** [comment]
Hey [vczb](https://github.com/vczb), can you assign me this task so that I can work on it?

**Comment by vczb** [comment]
> @vczb Can you assign me this issue? I would like to work on it

yes, thanks. feel free to work on it

**Comment by vczb** [comment]
> Hey [vczb](https://github.com/vczb), can you assign me this task so that I can work on it?

hi @yamitrvg12 , this issue is currently assigned to other dev. Jump in other issue or create a new one! thanks a lot

**Comment by vczb** [comment]
> Hey [vczb](https://github.com/vczb), can you assign me this task so that I can work on it?

hi @yamitrvg12 are you still working on that?

**Comment by PuBHARGAVI** [comment]
Hi @vczb, i would like to work on this. Can you assign this task to me?

**Comment by vaibhavshah03** [comment]
Can you assign me this issue? I would like to work on it

**Comment by vczb** [comment]
> Can you assign me this issue? I would like to work on it

hey @vaibhavshah03 , there are someone working on it right now, thanks for yout interest. please feel free to jump on other issue :)
