### ISSUE TITLE
Fix skipped tests

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#95]
there are some skipped tests under the codebase, please fix it :raised_hands:

**Comment by printf-ana** [comment]
Hey, I'm participanting of hacktoberfest and I would like to take this issue, could you please assign for me?

**Comment by vczb** [comment]
> Hey, I'm participanting of hacktoberfest and I would like to take this issue, could you please assign for me?

thanks for coming, go ahead! :rocket:

**Comment by vczb** [comment]
closed by https://github.com/vczb/sagu-ui/pull/102
